development:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: lit_development
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: lit_test
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: lit
  host: localhost
